apiVersion: v1 
kind: Pod 
metadata: 
  name: my-init-container 
spec: 
  initContainers: 
  - name: init 
    image: busybox:stable 
    command: ["sh", "-c", "sleep 60"]
  containers: 
  - name: nginx 
    image: nginx:stable