apiVersion: v1 
kind: Pod 
metadata: 
  name: my-pvc-pod 
spec: 
  containers: 
  - name: nginx 
    image: nginx:stable 
    volumeMount: 
    - name: my-data 
      mountPath: /data 
  volumes: 
  - name: my-data 
    persistentVolumeClaim: 
      claimName: my-pvc
