apiVersion: v1 
kind: PersistentVolume 
metadata: 
  name: my-pv 
spec: 
  storageClassName: host-pv 
  capacity: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath: 
    path: /etc/hostPath 
    type: Directory